apiVersion: apps/v1
kind: Deployment
metadata:
  name: $EKS
  labels:
     app: $EKS
spec:
  replicas: 10
  selector:
    matchLabels:
      app: $EKS
  template:
    metadata:
      labels:
        app: $EKS
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: phpapp-ctr
        image: $IMAGE_PHP:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
      app: $EKS
spec:
  selector:
    app: $EKS
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer